version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root where package.json & pnpm-lock.yaml live
    schedule:
      interval: "weekly" # Weekly keeps noise low; change to daily if desired
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
