version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root where package.json & pnpm-lock.yaml live
    schedule:
      interval: "daily" # Changed to daily for more frequent updates
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
